In [1]:
import pandas as pd
from sklearn.datasets import load_digits

In [2]:
digit = load_digits()

In [3]:
digit.data[:5]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
        14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
         1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
         0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  

In [5]:
digit.feature_names[:5]

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4']

In [6]:
digit.target[:5]

array([0, 1, 2, 3, 4])

In [7]:
digit.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# LET'S GET READY MODEL PARAMETERS FOR GRID SEARCH
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

model_params = {
    'svm': {
        'model': SVC(),
        'params': {
            'C': [1, 10, 20, 30, 40],
            'kernel': ['rbf', 'linear'],
            'gamma':['scale', 'auto']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10, 15, 20]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(),
        'params': {
            'C': [1, 5, 10, 15, 20]
        }
    },
    'naive_bayes_gaussian': {
        'model': GaussianNB(),
        'params': {}
    },
    'naive_bayes_multinomial': {
        'model': MultinomialNB(),
        'params': {}
    },
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy'],
            
        }
    }     
}

In [39]:
# LET'S USE GRID SEARCH TO FIND BEST MODEL, BEST SCORE, AND BEST ESTIMATORS
result = []
from sklearn.model_selection import GridSearchCV
for model_name, model_param in model_params.items():
    search = GridSearchCV(model_param['model'], model_param['params'], cv=5, return_train_score=False)
    search.fit(digit.data, digit.target)
    result.append({
        'model': model_name,
        'best_params': search.best_params_,
        'best_Score': search.best_score_
    })
result

/Users/shiva/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/shiva/ml_env/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Pl

[{'model': 'svm',
  'best_params': {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  'best_Score': np.float64(0.9738502011761063)},
 {'model': 'random_forest',
  'best_params': {'n_estimators': 15},
  'best_Score': np.float64(0.9254580625193439)},
 {'model': 'logistic_regression',
  'best_params': {'C': 1},
  'best_Score': np.float64(0.9137650882079852)},
 {'model': 'naive_bayes_gaussian',
  'best_params': {},
  'best_Score': np.float64(0.8069281956050759)},
 {'model': 'naive_bayes_multinomial',
  'best_params': {},
  'best_Score': np.float64(0.8703497369235531)},
 {'model': 'decision_tree',
  'best_params': {'criterion': 'entropy'},
  'best_Score': np.float64(0.7969049829774063)}]

In [40]:
search_df = pd.DataFrame(result)
search_df

model  ... best_Score
0                      svm  ...   0.973850
1            random_forest  ...   0.925458
2      logistic_regression  ...   0.913765
3     naive_bayes_gaussian  ...   0.806928
4  naive_bayes_multinomial  ...   0.870350
5            decision_tree  ...   0.796905

[6 rows x 3 columns]