In [179]:
import pandas as pd

In [180]:
df = pd.read_csv("datasets/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [181]:
df.columns

Index(['PassengerId', 'Name', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

In [182]:
selected_columns = ['Pclass', 'Sex', 'Age', 'Fare', 'Survived']
df = df[selected_columns]
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [183]:
# CHECK FOR NULL VALUES
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   Fare      891 non-null    float64
 4   Survived  891 non-null    int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 34.9+ KB


In [184]:
# GET MEAN FOR AVERAGE
mean_age = df['Age'].mean()
mean_age

np.float64(29.69911764705882)

In [185]:
# FILL NULL VALUE OF AGE
df['Age']=df['Age'].fillna(mean_age)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       891 non-null    float64
 3   Fare      891 non-null    float64
 4   Survived  891 non-null    int64  
dtypes: float64(2), int64(2), object(1)
memory usage: 34.9+ KB


In [187]:
# LABEL ENCODE SEX COLUMN AS IT IS NOMINAL
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df.head()

Pclass  Sex   Age     Fare  Survived
0       3    1  22.0   7.2500         0
1       1    0  38.0  71.2833         1
2       3    0  26.0   7.9250         1
3       1    0  35.0  53.1000         1
4       3    1  35.0   8.0500         0

In [188]:
# INDEPENDENT VARIABLE
X=df[['Pclass', 'Sex', 'Age', 'Fare']]
X.head()

Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    0  38.0  71.2833
2       3    0  26.0   7.9250
3       1    0  35.0  53.1000
4       3    1  35.0   8.0500

In [189]:
# DEPENDENT VARIABLE
y = df[['Survived']]
y.head()

Survived
0         0
1         1
2         1
3         1
4         0

In [190]:
# SINCE THE GENDER COLUMN IS IN TEXT, DO ONE-HOT ENCODING
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('gender_enc', OneHotEncoder(drop='first', handle_unknown='ignore'), ['Sex'])
    ],
    remainder = 'passthrough'
)

In [191]:
X=ct.fit_transform(X)

In [192]:
X

array([[ 1.        ,  3.        , 22.        ,  7.25      ],
       [ 0.        ,  1.        , 38.        , 71.2833    ],
       [ 0.        ,  3.        , 26.        ,  7.925     ],
       ...,
       [ 0.        ,  3.        , 29.69911765, 23.45      ],
       [ 1.        ,  1.        , 26.        , 30.        ],
       [ 1.        ,  3.        , 32.        ,  7.75      ]],
      shape=(891, 4))

In [193]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_tesy = train_test_split(X, y)

In [194]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

/Users/shiva/ml_env/lib/python3.13/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [195]:
model.score(X_test, y_tesy)

0.8071748878923767

In [196]:
y[:10]

Survived
0         0
1         1
2         1
3         1
4         0
5         0
6         0
7         0
8         1
9         1

In [197]:
model.predict(X[:10])

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1])

In [198]:
model.predict_proba(X[:10])

array([[0.94639175, 0.05360825],
       [0.02692649, 0.97307351],
       [0.36542343, 0.63457657],
       [0.04553455, 0.95446545],
       [0.95214174, 0.04785826],
       [0.95104252, 0.04895748],
       [0.56692057, 0.43307943],
       [0.90267658, 0.09732342],
       [0.3671938 , 0.6328062 ],
       [0.1614583 , 0.8385417 ]])